### ISSUE TITLE
Probably a minor error in the file: samples/hello/hello_entry.rb

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-tk#11] opened 2022-07-27 19:01 UTC
Heya Andy,

I think I found a tiny error.

I get:

"Error: NoMethodError: undefined method 'foreground ...'"

Here is the copy/pasted message from that error widget:

    NoMethodError: undefined method `foreground=' for #<Glimmer::Tk::LabelProxy:0x00007f97c8704038 @parent_proxy=#    <Glimmer::Tk::RootProxy:0x00007f97c96ec888 @tk=#<Tk::Root:0x00007f97c972f318 @path=".">, @... >
    ---< backtrace of Ruby side >-----
    /root/.gem/gems/glimmer-dsl-tk-0.0.60/lib/glimmer/tk/widget_proxy.rb:573:in `rescue in method_missing'
    /root/.gem/gems/glimmer-dsl-tk-0.0.60/lib/glimmer/tk/widget_proxy.rb:560:in `method_missing'
    aha.rb:59:in `block (3 levels) in launch'
    /root/.gem/gems/tk-0.4.0/lib/tk/validation.rb:328:in `block in _initialize_for_cb_class'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1430:in `eval_cmd'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1430:in `cb_eval'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1385:in `call'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1582:in `block in callback'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1581:in `catch'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1581:in `callback'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1798:in `mainloop'
    /root/.gem/gems/tk-0.4.0/lib/tk.rb:1798:in `mainloop'
    /root/.gem/gems/glimmer-dsl-tk-0.0.60/lib/glimmer/tk/root_proxy.rb:69:in `start_event_loop'
    /root/.gem/gems/glimmer-dsl-tk-0.0.60/lib/glimmer/tk/root_proxy.rb:43:in `open'
    aha.rb:86:in `launch'
    aha.rb:94:in `<main>'
    ---< backtrace of Tk side >-------
        invoked from within
    "rb_out c00009 555-555-5555e e key .w00005 1 12 555-555-5555 key "
    	(in -invalidcommand validation command executed by .w00005)
        invoked from within
    "$w insert insert $s"
        (procedure "ttk::entry::Insert" line 4)
        invoked from within
    "ttk::entry::Insert .w00005 e "
        (command bound to event)

I get this error when I enter anything in the entry for phone number
e. g. when I add non numbers at the least. But it shows up only
once, then I can continue to type without causing this error widget
to show up.

It's a tiny thing but I just mention it in case you want to fix it.

I''ll also copy/paste the .rb code in case you can not find the file I
mean:

    require 'glimmer-dsl-tk'

    class HelloEntry
      include Glimmer
  
      attr_accessor :default, :password, :telephone, :read_only
  
      def initialize
        self.default = 'default'
        self.password = 'password'
        self.telephone = '555-555-5555'
        self.read_only = 'Telephone area code is 555'
      end
  
      def launch
        root {
          title 'Hello, Entry!'
          minsize 230, 0
         
          label {
            grid sticky: 'ew'
            text 'default entry'
          }
          entry { |the_entry|
            grid sticky: 'ew'
            text <=> [self, :default]
          }
      
          label {
            grid sticky: 'ew'
            text 'password entry'
          }
          entry {
            grid sticky: 'ew'
            show '*'
            text <=> [self, :password]
          }

          @validated_entry_label = label {
            grid sticky: 'ew'
            text 'entry with event handlers'
          }
          entry { |the_entry|
            grid sticky: 'ew'
            text <=> [self, :telephone]

            # validate 'key' # default when on('validate') or on('invalid') is specified
            ## Validation happens on key change by default when validation listeners are specified
            ## (other accepted values: 'none', 'focus', 'focusin', 'focusout', 'key', or 'all')
        
            ## this event kicks in just after the user typed and before modifying the text variable
            on('validate') do |new_text_variable|
              telephone?(new_text_variable.value)
            end

            ## this event kicks in just after the text variable is validated and before it is modified
            on('invalid') do |validate_args|
              @validated_entry_label.text = "#{validate_args.value} is not a valid phone!"
              @validated_entry_label.foreground = 'red'
            end

            ## this event kicks in just after the text variable is validated and modified
            on('change') do |new_text_variable|
              self.read_only = "Telephone area code is #{new_text_variable.value.gsub(/[^0-9]/, '')[0...3]}"
              @validated_entry_label.text = 'entry with event handlers'
              @validated_entry_label.foreground = nil
            end
        
            ## this is similar to on('change') (which is Glimmer-specific), but more low level at the Tk level
            ## it is the equivalent of calling: the_entry.tk.textvariable.trace('write') { puts "..." }
            ## More at: https://tkdocs.com/tutorial/widgets.html#entry and https://tcl.tk/man/tcl8.6/TclCmd/trace.htm#M14
            on_textvariable('write') do
              puts "\"#{the_entry.text}\" has been written to entry!"
            end
          }

          label {
            grid sticky: 'ew'
            text 'read-only entry'
          }
          entry {
            grid sticky: 'ew'
            text <=> [self, :read_only]
            readonly true
          }
        }.open
      end
  
      def telephone?(text)
        !!text.match(/^\d{0,3}[-.\/]?\d{0,3}[-.\/]?\d{0,4}$/)
      end
    end

    HelloEntry.new.launch

**Comment by AndyObtiva** [comment] 2022-07-27 21:49
Thank you for reporting. This error was caused by the new feature added in 0.0.60 that auto-converts hex colors missing the '#' prefix to a hex color with '#' prefix (e.g. 'FFA3B4' becomes '#FFA3B4'). The issue was that the color 'red' was getting mistaken as hex color and converted to '#red'. 

In any case, this is fixed in v0.0.61

https://rubygems.org/gems/glimmer-dsl-tk/versions/0.0.61

![Screen Shot 2022-07-27 at 5 47 06 PM](https://user-images.githubusercontent.com/23052/181378671-34356254-1a23-4b4c-bf99-7702855ca893.png)

Cheers!

**Closed as completed by AndyObtiva** 2022-07-27 21:49 UTC
